name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install format dependencies
      run: |
        pip3 install cmake_format==0.6.13 pyyaml

    - name: configure
      run: cmake -Htest -Bbuild

    - name: check style
      run: cmake --build build --target check-format
