name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [ 'g++-10', 'clang++' ]

    env:
      CXX: ${{ matrix.compiler }}
    
    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build build -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug

    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"